services:
  santa-game:
    build: .
    container_name: santa-game
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./scores.json:/app/scores.json
    restart: unless-stopped
